name: python and node install build start workflow

# 什麼情況下觸發 workflow
on:
  # 對於 main branch 建立 Branch 與 Pull Request 時觸發 workflow 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: debian-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    # - name: Add conda to system path
    #   run: |
    #     # $CONDA is an environment variable pointing to the root of the miniconda directory
    #     echo $CONDA/bin >> $GITHUB_PATH
    # - name: Install dependencies
    #   run: |
    #     conda env update --file environment.yml --name base
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pip_requirements.txt 
    - name: Install node dependencies
      run: |
        npm install
    - name: Build npm
      run: npm run build
    - name: start npm
      run: npm run start
